### ISSUE TITLE
Migrate to flutter 2.0+ and add null safety support

### ISSUE THREAD

**Issue by champ96k** [thruthesky/audio_wave#4]
Flutter 2.0+ null safety support not available.

**Comment by champ96k** [comment]
@thruthesky can you please assign me, i would love to take it , Thanks:)

**Comment by thruthesky** [comment]
@champ96k Hi, champ96k. I didn't noticed there was an issue. Fortunately, somebody already did the job and request for PR. And I merged it and released new version.
You may try now.
